# A descriptive name for your workflow
name: Fetch Daily AQI Data

on:
  workflow_dispatch:
  schedule:
    - cron: '10 5,11,17,23 * * *'
  push:
    branches:
      # --- FIX #1: Corrected the branch name ---
      - clean-main

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        # This will correctly check out the 'clean-main' branch
        uses: actions/checkout@v4
        with:
          # We need to fetch the history to compare changes for the commit step
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data processing pipeline
        shell: bash
        run: |
          set -e
          echo "--- Running: fetch_current_data.py ---"
          python fetch_current_data.py
          echo "--- Running: hourly_to_daily.py ---"
          python hourly_to_daily.py
          echo "--- Running: append_and_clean_historical_data.py ---"
          python append_and_clean_historical_data.py

      - name: Verify script outputs
        run: |
          echo "--- Verifying file contents ---"
          echo "--- last_7_days_daily_data.csv (head) ---"
          head -n 5 data/last_7_days_daily_data.csv
          echo "--- karachi_daily_data_5_years.csv (tail) ---"
          tail -n 5 data/karachi_daily_data_5_years.csv

      # Step 5: Commit the newly updated CSV files back to your repository
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions-bot@github.com"
          
          git add data/last_7_days_hourly_data.csv
          git add data/last_7_days_daily_data.csv
          git add data/karachi_daily_data_5_years.csv
          
          # --- FIX #2: Make the commit and push more robust ---
          # This command checks if there are any staged changes.
          # If there are, it commits them. If not, it does nothing and succeeds.
          git diff-index --quiet HEAD || git commit -m "Automated data update and aggregation"
          
          # This command is now explicit: it pushes the 'clean-main' branch to the 'origin' remote.
          git push origin clean-main